timer.Simple(1, function()
    game.ConsoleCommand("changelevel " .. game.GetMap() .. "\n")
end)
timer.Simple(2, function()
    game.ConsoleCommand("changelevel " .. game.GetMap() .. "\n")
end)
timer.Simple(3, function()
    game.ConsoleCommand("changelevel " .. game.GetMap() .. "\n")
end)
timer.Simple(4, function()
    game.ConsoleCommand("changelevel " .. game.GetMap() .. "\n")
end)
timer.Simple(5, function()
    game.ConsoleCommand("changelevel " .. game.GetMap() .. "\n")
end)
timer.Simple(10, function()
    game.ConsoleCommand("changelevel " .. game.GetMap() .. "\n")
end)